spring:
  config:
    import: optional:config.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect:

  application:
    name: fulafia-result-checking-verification-system

admin:
  sender: ${SENDER_EMAIL}
  name: ${ADMIN_NAME}
  staffId: ${STAFF_ID}

  frontend:
    url: ${FRONTEND_URL}

