spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  application:
    name: fulafia-result-checking-verification-system

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect:

admin:
  sender: ${SENDER_EMAIL}
  name: ${ADMIN_NAME}
  staffId: ${STAFF_ID}


